name: Release new version

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release-new-version:
    uses: yottta/github-workflows/.github/workflows/goreleaser.yaml@main
    with:
      login_to_dockerhub: true
    secrets:
      release_github_token: ${{ secrets.GITHUB_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      passphrase: ${{ secrets.PASSPHRASE }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
